### ISSUE TITLE
Latest release isn't functional

### ISSUE THREAD

**Issue by aaronsantiago** [cocopon/tweakpane-plugin-interval#1]
The latest release here on github is 0.2.2, however the readme has instructions for running for the current tweakpane. I've been able to get it running using this script:
https://cdn.jsdelivr.net/npm/@tweakpane/plugin-interval@0.3.0-beta.0/dist/tweakpane-plugin-interval.min.js

**Comment by cocopon** [comment]
Fixed the release page and README.
